version: "3.7"

services:
  backend:
    container_name: php_web_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
    - .:/src/app/myapp
    ports:
      - 8080:8080
  db:
    container_name: database_php_web_app
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      volumes:
        .dbdata:/var/lib/mysql
      ports:
        3307:3306